name: 'build-component-multi-arch'
description: 'Build Multi-Arch Container'
inputs:
  acr_repo:
    description: Azure Container Registry
    required: true
  acr_name:
    description: Azure Container Registry name
    required: true
  acr_password:
    description: Azure Container Registry password
    required: true
  container_name:
    description: Component container name
    required: true
  makefile_component_name:
    description: Component prefix used by Makefile
    required: true
  github_event_name:
    description: Specify the github event name (push, pull_request, release, etc)
    required: true
runs:
  using: 'node12'
  main: 'main.js'
